// Generated by ReScript, PLEASE EDIT WITH CARE


var StyleProvider;

var $$Text;

var Flex;

var Switch;

var Logos;

var Fonts;

export {
  StyleProvider ,
  $$Text ,
  Flex ,
  Switch ,
  Logos ,
  Fonts ,
}
/* No side effect */
