// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import InterBoldWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-Bold.woff2";
import InterMediumWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-Medium.woff2";
import InterRegularWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-Regular.woff2";
import InterSemiBoldWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-SemiBold.woff2";
import InterExtraBoldWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-ExtraBold.woff2";
import InterLightBETAWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-Light-BETA.woff2";
import HMAlphaMonoMediumWoff2 from "@ledgerhq/react-ui/assets/fonts/HMAlphaMono-Medium.woff2";
import InterExtraLightBETAWoff2 from "@ledgerhq/react-ui/assets/fonts/Inter-ExtraLight-BETA.woff2";

var fontMap = Js_dict.fromArray([
      [
        "HMAlphaMono-Medium",
        HMAlphaMonoMediumWoff2
      ],
      [
        "Inter-Bold",
        InterBoldWoff2
      ],
      [
        "Inter-ExtraBold",
        InterExtraBoldWoff2
      ],
      [
        "Inter-ExtraLight-BETA",
        InterExtraLightBETAWoff2
      ],
      [
        "Inter-Light-BETA",
        InterLightBETAWoff2
      ],
      [
        "Inter-Medium",
        InterMediumWoff2
      ],
      [
        "Inter-Regular",
        InterRegularWoff2
      ],
      [
        "Inter-SemiBold",
        InterSemiBoldWoff2
      ]
    ]);

export {
  fontMap ,
}
/* fontMap Not a pure module */
