// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Hello(props) {
  return JsxRuntime.jsx("h1", {
              children: "Hello World",
              className: "text-3xl font-bold underline"
            });
}

var make = Hello;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
