// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as Hello$RescriptProjectTemplate from "./components/Hello.mjs";

import "./index.css";
;

((async function (param) {
        var request = await fetch("https://jsonplaceholder.typicode.com/posts/1").then(function (prim) {
              return prim.json();
            });
        console.log(request);
      })(undefined));

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(Hello$RescriptProjectTemplate.make, {}));
}

export {
  
}
/*  Not a pure module */
