// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as Root$RescriptProjectTemplate from "./components/Root.mjs";

((async function (param) {
        var request = await fetch("https://jsonplaceholder.typicode.com/posts/1").then(function (prim) {
              return prim.json();
            });
        console.log(request);
      })(undefined));

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(Root$RescriptProjectTemplate.make, {}));
}

export {
  
}
/*  Not a pure module */
